# Use official Python image
FROM python:3.11-slim

WORKDIR /app

COPY hello.py .
COPY requirements.txt .

# Install dependencies (none for now)
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "hello.py"]
